// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: internal/catalog/recordpb/record.proto

package recordpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          []byte                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_internal_catalog_recordpb_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_internal_catalog_recordpb_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_internal_catalog_recordpb_record_proto_rawDescGZIP(), []int{0}
}

func (x *Attribute) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Attribute) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Path is supplied by the database key, never duplicated in the record value.
type Record struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	AttributesStatus string                 `protobuf:"bytes,2,opt,name=attributes_status,json=attributesStatus,proto3" json:"attributes_status,omitempty"`
	Algorithm        string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Hash             []byte                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Target           []byte                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Acl              []*Attribute           `protobuf:"bytes,6,rep,name=acl,proto3" json:"acl,omitempty"`
	Xattrs           []*Attribute           `protobuf:"bytes,7,rep,name=xattrs,proto3" json:"xattrs,omitempty"`
	Size             int64                  `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	Inode            uint64                 `protobuf:"varint,9,opt,name=inode,proto3" json:"inode,omitempty"`
	Mtime            int64                  `protobuf:"varint,10,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Ctime            int64                  `protobuf:"varint,11,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Btime            int64                  `protobuf:"varint,12,opt,name=btime,proto3" json:"btime,omitempty"`
	HashedAt         int64                  `protobuf:"varint,13,opt,name=hashed_at,json=hashedAt,proto3" json:"hashed_at,omitempty"`
	Observed         int64                  `protobuf:"varint,14,opt,name=observed,proto3" json:"observed,omitempty"`
	Nlink            uint64                 `protobuf:"varint,15,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Atime            int64                  `protobuf:"varint,16,opt,name=atime,proto3" json:"atime,omitempty"`
	Device           uint64                 `protobuf:"varint,17,opt,name=device,proto3" json:"device,omitempty"`
	Gid              uint32                 `protobuf:"varint,18,opt,name=gid,proto3" json:"gid,omitempty"`
	Uid              uint32                 `protobuf:"varint,19,opt,name=uid,proto3" json:"uid,omitempty"`
	Mode             uint32                 `protobuf:"varint,20,opt,name=mode,proto3" json:"mode,omitempty"`
	NoAtime          bool                   `protobuf:"varint,21,opt,name=no_atime,json=noAtime,proto3" json:"no_atime,omitempty"`
	HasBtime         bool                   `protobuf:"varint,22,opt,name=has_btime,json=hasBtime,proto3" json:"has_btime,omitempty"`
	TimesInSeconds   bool                   `protobuf:"varint,23,opt,name=times_in_seconds,json=timesInSeconds,proto3" json:"times_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_internal_catalog_recordpb_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_internal_catalog_recordpb_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_internal_catalog_recordpb_record_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Record) GetAttributesStatus() string {
	if x != nil {
		return x.AttributesStatus
	}
	return ""
}

func (x *Record) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *Record) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Record) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Record) GetAcl() []*Attribute {
	if x != nil {
		return x.Acl
	}
	return nil
}

func (x *Record) GetXattrs() []*Attribute {
	if x != nil {
		return x.Xattrs
	}
	return nil
}

func (x *Record) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Record) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Record) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *Record) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *Record) GetBtime() int64 {
	if x != nil {
		return x.Btime
	}
	return 0
}

func (x *Record) GetHashedAt() int64 {
	if x != nil {
		return x.HashedAt
	}
	return 0
}

func (x *Record) GetObserved() int64 {
	if x != nil {
		return x.Observed
	}
	return 0
}

func (x *Record) GetNlink() uint64 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *Record) GetAtime() int64 {
	if x != nil {
		return x.Atime
	}
	return 0
}

func (x *Record) GetDevice() uint64 {
	if x != nil {
		return x.Device
	}
	return 0
}

func (x *Record) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Record) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Record) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Record) GetNoAtime() bool {
	if x != nil {
		return x.NoAtime
	}
	return false
}

func (x *Record) GetHasBtime() bool {
	if x != nil {
		return x.HasBtime
	}
	return false
}

func (x *Record) GetTimesInSeconds() bool {
	if x != nil {
		return x.TimesInSeconds
	}
	return false
}

var File_internal_catalog_recordpb_record_proto protoreflect.FileDescriptor

const file_internal_catalog_recordpb_record_proto_rawDesc = "" +
	"\n" +
	"&internal/catalog/recordpb/record.proto\x12\x13fsledger.catalog.v1\"5\n" +
	"\tAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\fR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x80\x05\n" +
	"\x06Record\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12+\n" +
	"\x11attributes_status\x18\x02 \x01(\tR\x10attributesStatus\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\fR\x04hash\x12\x16\n" +
	"\x06target\x18\x05 \x01(\fR\x06target\x120\n" +
	"\x03acl\x18\x06 \x03(\v2\x1e.fsledger.catalog.v1.AttributeR\x03acl\x126\n" +
	"\x06xattrs\x18\a \x03(\v2\x1e.fsledger.catalog.v1.AttributeR\x06xattrs\x12\x12\n" +
	"\x04size\x18\b \x01(\x03R\x04size\x12\x14\n" +
	"\x05inode\x18\t \x01(\x04R\x05inode\x12\x14\n" +
	"\x05mtime\x18\n" +
	" \x01(\x03R\x05mtime\x12\x14\n" +
	"\x05ctime\x18\v \x01(\x03R\x05ctime\x12\x14\n" +
	"\x05btime\x18\f \x01(\x03R\x05btime\x12\x1b\n" +
	"\thashed_at\x18\r \x01(\x03R\bhashedAt\x12\x1a\n" +
	"\bobserved\x18\x0e \x01(\x03R\bobserved\x12\x14\n" +
	"\x05nlink\x18\x0f \x01(\x04R\x05nlink\x12\x14\n" +
	"\x05atime\x18\x10 \x01(\x03R\x05atime\x12\x16\n" +
	"\x06device\x18\x11 \x01(\x04R\x06device\x12\x10\n" +
	"\x03gid\x18\x12 \x01(\rR\x03gid\x12\x10\n" +
	"\x03uid\x18\x13 \x01(\rR\x03uid\x12\x12\n" +
	"\x04mode\x18\x14 \x01(\rR\x04mode\x12\x19\n" +
	"\bno_atime\x18\x15 \x01(\bR\anoAtime\x12\x1b\n" +
	"\thas_btime\x18\x16 \x01(\bR\bhasBtime\x12(\n" +
	"\x10times_in_seconds\x18\x17 \x01(\bR\x0etimesInSecondsB7Z5github.com/inode64/fsledger/internal/catalog/recordpbb\x06proto3"

var (
	file_internal_catalog_recordpb_record_proto_rawDescOnce sync.Once
	file_internal_catalog_recordpb_record_proto_rawDescData []byte
)

func file_internal_catalog_recordpb_record_proto_rawDescGZIP() []byte {
	file_internal_catalog_recordpb_record_proto_rawDescOnce.Do(func() {
		file_internal_catalog_recordpb_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_catalog_recordpb_record_proto_rawDesc), len(file_internal_catalog_recordpb_record_proto_rawDesc)))
	})
	return file_internal_catalog_recordpb_record_proto_rawDescData
}

var file_internal_catalog_recordpb_record_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_catalog_recordpb_record_proto_goTypes = []any{
	(*Attribute)(nil), // 0: fsledger.catalog.v1.Attribute
	(*Record)(nil),    // 1: fsledger.catalog.v1.Record
}
var file_internal_catalog_recordpb_record_proto_depIdxs = []int32{
	0, // 0: fsledger.catalog.v1.Record.acl:type_name -> fsledger.catalog.v1.Attribute
	0, // 1: fsledger.catalog.v1.Record.xattrs:type_name -> fsledger.catalog.v1.Attribute
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_catalog_recordpb_record_proto_init() }
func file_internal_catalog_recordpb_record_proto_init() {
	if File_internal_catalog_recordpb_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_catalog_recordpb_record_proto_rawDesc), len(file_internal_catalog_recordpb_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_catalog_recordpb_record_proto_goTypes,
		DependencyIndexes: file_internal_catalog_recordpb_record_proto_depIdxs,
		MessageInfos:      file_internal_catalog_recordpb_record_proto_msgTypes,
	}.Build()
	File_internal_catalog_recordpb_record_proto = out.File
	file_internal_catalog_recordpb_record_proto_goTypes = nil
	file_internal_catalog_recordpb_record_proto_depIdxs = nil
}
